{
    'name': 'Odoo Whatsapp Integration',
    'version': '14.0.2.1.2',
    'category' : 'Odex25-base',
    'summary': """Odoo Whatsapp Integration For Sales,Contacts,Crm,Stock,Purchase,Invoice, and Floating button in Website""",
    'description': """Added options for sending Whatsapp messages and Mails in systray bar,sale order, invoices, 
    website portal view and share the access url of documents using share option available in each records through 
    Whatsapp web..""",
    'author': 'Expert',
    'website': "https://www.cybrosys.com",
    'company': 'Expert',
    'depends': ['base','contacts','crm','stock','sale_management','purchase', 'account', 'website'],
    'data': [
        'views/assets.xml',
        'views/portal_whatsapp_view.xml',
        'views/sale_order_inherited.xml',
        'views/purchase_order_inherited.xml',
        'views/stock_picking_inherit.xml',
        'views/crm_lead.xml',
        'views/account_move_inherited.xml',
        'views/contacts.xml',
        'views/website_inherited.xml',
        'wizard/wh_message_wizard.xml',
        'wizard/portal_share_inherited.xml',
        'security/ir.model.access.csv',
    ],
    'qweb': [
        'static/src/xml/whatsapp_button.xml',
        'static/src/xml/mail_button.xml',
    ],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}